# Generated by Django 3.2.19 on 2023-05-31 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='publicacao',
            table='publicacao',
        ),
    ]
