# Generated by Django 3.2.19 on 2023-06-01 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_rename_publicaco_comentario_publicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
